#!/usr/bin/env sh

cp -R ~/.config/nvim/ macos/.config/
cp -R ~/.config/starship.toml macos/.config/
cp ~/.gitconfig macos/
cp ~/.gitconfig.personal macos/
cp ~/.zshrc macos/
cp ~/.tmux.conf macos/

git add . && PRE_COMMIT_ALLOW_NO_CONFIG=1 git commit -m "$*" && git push
