# eval "$(starship init zsh)"

#########################################################################################
# BEGIN VCS INFO
#
# Load version control information module
autoload -Uz vcs_info

# this has been taken and modified based on the example shown here:
# https://github.com/zsh-users/zsh/blob/master/Misc/vcs_info-examples#L44
function precmd() {
    vcs_info

    prompt_newline=$'\n%{\r%}'

    if [[ -z ${vcs_info_msg_0_} ]]; then
        PS1="${prompt_newline}%B%5~%b %#${prompt_newline}> "
    else
        PS1="${prompt_newline}%B%3~${vcs_info_msg_0_}%b %#${prompt_newline}> "
    fi
}

function +vi-git-ahead-behind() {
    local ahead behind
    local -a gitstatus

    # Exit early in case the worktree is on a detached HEAD
    git rev-parse ${hook_com[branch]}@{upstream} >/dev/null 2>&1 || return 0

    local -a ahead_and_behind=(
        $(git rev-list --left-right --count HEAD...${hook_com[branch]}@{upstream} 2>/dev/null)
    )

    ahead=${ahead_and_behind[1]}
    behind=${ahead_and_behind[2]}

    (( $ahead )) && gitstatus+=( "+${ahead}" )
    (( $behind )) && gitstatus+=( "-${behind}" )

    hook_com[misc]+=${(j:/:)gitstatus}
}

function +vi-git-status-counts() { 
    local status_output
    status_output=$(git status --porcelain 2>/dev/null)
    
    local stash_count=$(git stash list 2>/dev/null | wc -l | tr -d ' ')
    
    local -a counts
    
    if [[ -n $status_output ]]; then
        # Staged: A, M, D, R, C in the FIRST column
        local staged=$(echo "$status_output" | grep -c '^[AMDRE]')
        # Modified: M in the SECOND column
        local modified=$(echo "$status_output" | grep -c '^.M')
        # Deleted: D in the FIRST or SECOND column
        local deleted=$(echo "$status_output" | grep -c '^.D')
        # Untracked: ??
        local untracked=$(echo "$status_output" | grep -c '??')

        (( $staged > 0 ))    && counts+=( "++(${staged})" )
        (( $modified > 0 ))  && counts+=( "M${modified}" )
        (( $untracked > 0 )) && counts+=( "U${untracked}" )
        (( $deleted > 0 ))   && counts+=( "D${deleted}" )
    fi

    # Check stash regardless of porcelain output
    (( $stash_count > 0 )) && counts+=( "S${stash_count}" ) # 

    # Append to misc so it shows up via %m
    if (( ${#counts} > 0 )); then
        hook_com[misc]+=" [${(j: :)counts}]"
    fi
}

zstyle ':vcs_info:*' check-for-changes true
zstyle ':vcs_info:git*' formats " - %b %m " 
zstyle ':vcs_info:git*+set-message:*' hooks git-ahead-behind git-status-counts

#
# END VCS INFO
#########################################################################################


[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
source <(fzf --zsh)

alias fzf='fzf --preview="cat -n {}"'

# initialize autocomplete
autoload -Uz compinit add-zsh-hook
compinit

bindkey -e
bindkey '[C' forward-word
bindkey '[D' backward-word

# mv files the smart way!
# This
#   mmv *.md *.txt
# will change all files ending with .md into .txt
autoload zmv
alias mmv='noglob zmv -W'

# Open buffer line in editor
autoload -Uz edit-command-line
zle -N edit-command-line
bindkey '^xe' edit-command-line
bindkey -s '^xgc' 'git commit -am ""\C-b'

export EDITOR="nvim"

##########################################################################################

# Git
export PATH="/opt/homebrew/Cellar/git/2.?.?/bin:$PATH"
# LLVM
export PATH="/opt/homebrew/Cellar/llvm/17.?.?/bin:$PATH"
# MySQL
export PATH="/opt/homebrew/Cellar/mysql-client/8.?.?/bin:$PATH"

alias reload!='RELOAD=1 source ~/.zshrc'
alias l='ls -lhtF --color=always'
alias la='ls -alhF --color=always'
alias ..='cd ..'

alias grep='grep --color=always'
alias df='df -h'    # disk free, in Gigabytes, not bytes
alias du='du -h -c' # calculate disk usage for a folder
alias mkdir='mkdir -p'

mcd () { mkdir "$@" && cd "$@"; }

# git sauce
gs () { git status; }
gd () { git diff; }

# setenv is implemented relying on zsh capabilites. So be aware of it.
setenv () {
  local file # prevents overwriting a global var named 'file' in my current term session.
  [[ -f .env ]] && file=".env" || { [[ -f .envrc ]] && file=".envrc"; }

  # The ${file:?} syntax throws an error if 'file' is empty or unset
  # ':' checks if the var is null or unset. '?' exit or print operator.
  : ${file:?"No .env or .envrc found"}

  printf "Sourcing %s...\n" "$file"
  set -a && source "$file" && set +a
}

# set TIGER as the token generated by fury tiger token
settiger() { export TIGER=$(fury get-token | awk -F"Bearer" '{print $0}') }

# move to mplay
dev() { cd /Users/psoto/Developer/mplay }

# # python stuff for venv management (this makes pre-commit work)
# export PYENV_ROOT="$HOME/.pyenv"
# command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"
# eval "$(pyenv init -)"


# golang
export PATH="/Users/psoto/go/bin:$PATH"
export GOPRIVATE=github.com/mercadolibre,github.com/melisource,github.com/psoto_meli
export GONOSUMDB=github.com/mercadolibre,github.com/melisource,github.com/psoto_meli
export GONOPROXY="https://go.artifacts.furycloud.io/"
export GOPROXY="https://go.artifacts.furycloud.io/"

# clang
# otherwise it won't find header files
export SDKROOT=$(xcrun --sdk macosx --show-sdk-path)

# locale
export LANG="en_US.UTF-8"
export LC_CTYPE="en_US.UTF-8"

# # The following line is added by pre-commit
# export PATH="/opt/homebrew/bin:$PATH"

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
export PATH="/Users/psoto/.tvlabs/bin:$PATH"


# pnpm
export PNPM_HOME="/Users/psoto/Library/pnpm"
case ":$PATH:" in
  *":$PNPM_HOME:"*) ;;
  *) export PATH="$PNPM_HOME:$PATH" ;;
esac
# pnpm end

source ~/.yara/wrappers/node.sh


export PATH="$PATH:/Users/psoto/Library/Python/3.9/bin"
export RANGER_FURY_LOCATION=/Users/psoto/.fury #Added by Fury CLI
export RANGER_FURY_VENV_LOCATION=/Users/psoto/.fury/fury_venv #Added by Fury CLI


# # JAVA thingies
# export JAVA_HOME="/Users/psoto/Library/Java/JavaVirtualMachines/corretto-11.0.27/Contents/Home"
# export PATH="$PATH:$JAVA_HOME"

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/psoto/Downloads/google-cloud-sdk/path.zsh.inc' ]; then . '/Users/psoto/Downloads/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/psoto/Downloads/google-cloud-sdk/completion.zsh.inc' ]; then . '/Users/psoto/Downloads/google-cloud-sdk/completion.zsh.inc'; fi


#
# BUILD AND LAUNCH WEBOS APP
#
websimulator() {
    MERCADOPLAY_CLI_BUILD=true pnpm run build webos || return # if pnpm run build fails, the shell won't run the launch command
    ares-launch -s 24 -sp /Users/psoto/Documents/webOS_TV_24_Simulator_1.4.1 ../dist/webos
}

#
# ENV VARS FOR MPLAY FRONTEND
#
export SECRET_BITMOVIN_PLAYER_LICENSE_KEY="dcbf46e6-c70f-400d-a0da-3d703fb6143d"
export SECRET_BITMOVIN_ANALYTICS_LICENSE_KEY="305e705f-9a21-4721-a400-4a5131b6ca7b"

#
# BUILD IPK
#
generateipk() {
    MERCADOPLAY_CLI_BUILD=true pnpm run build -- webos 6 || return # if pnpm run build fails, the shell won't run the launch command
    ares-package dist/webos6 -o ~/Downloads/ipk-webos -n
}

export PATH="$PATH:$HOME/Library/Android/sdk/platform-tools"

# Added by Python Dev Environment Installer
export HOMEBREW_BIN_LOCATION="/opt/homebrew/bin"
export PATH="$HOMEBREW_BIN_LOCATION:$PATH"
# Added by Python Dev Environment Installer

# export ANTHROPIC_MODEL="claude-sonnet-4-6[1m]"
export PATH="/Users/psoto/.local/bin:$PATH"

# Added by Fury CLI installation process
export FURY_BIN_LOCATION="/Users/psoto/.fury/fury_venv/bin"
export PATH="$PATH:$FURY_BIN_LOCATION"
# Added by Fury CLI installation process

# Internal Python Registry
export PIP_INDEX_URL='https://pypi.artifacts.furycloud.io/simple'
export UV_INDEX_URL='https://pypi.artifacts.furycloud.io/simple'

# CODEX 
alias codex-mcp='codex --config $HOME/.codex/config-mcp.toml'












# >>> es-wrapper initialize >>>
# Agregado automáticamente por el instalador de es-wrapper
# Para desinstalar, ejecuta: ~/.es-wrapper/uninstall.sh

_es_wrapper_prepend_path() {
    local _eswrap_dir="$HOME/.es-wrapper/bin"
    local _eswrap_path=":$PATH:"
    while [[ "$_eswrap_path" == *":$_eswrap_dir:"* ]]; do
        _eswrap_path="${_eswrap_path/:$_eswrap_dir:/:}"
    done
    if [[ -n "${NVM_BIN:-}" && -d "$NVM_BIN" ]]; then
        while [[ "$_eswrap_path" == *":$NVM_BIN:"* ]]; do
            _eswrap_path="${_eswrap_path/:$NVM_BIN:/:}"
        done
    fi
    _eswrap_path="${_eswrap_path#:}"
    _eswrap_path="${_eswrap_path%:}"
    if [[ -n "${NVM_BIN:-}" && -d "$NVM_BIN" ]]; then
        if [[ -n "$_eswrap_path" ]]; then
            export PATH="$_eswrap_dir:$NVM_BIN:$_eswrap_path"
        else
            export PATH="$_eswrap_dir:$NVM_BIN"
        fi
    elif [[ -n "$_eswrap_path" ]]; then
        export PATH="$_eswrap_dir:$_eswrap_path"
    else
        export PATH="$_eswrap_dir"
    fi
}
_es_wrapper_prepend_path

unalias source 2>/dev/null
unalias . 2>/dev/null
source() {
    builtin source "$@"
    local ret=$?
    if [[ -n "$VIRTUAL_ENV" ]]; then
        _es_wrapper_prepend_path
    fi
    return $ret
}
alias .='source'

_es_wrapper_guard() {
    _es_wrapper_prepend_path
}
if [[ " ${precmd_functions[*]-} " != *" _es_wrapper_guard "* ]]; then
    precmd_functions+=(_es_wrapper_guard)
fi

_es_wrapper_vm_hook() {
    if [[ -f .nvmrc || -f .node-version ]]; then
        type nvm &>/dev/null && nvm use --silent 2>/dev/null
    fi

    if [[ -f .python-version ]]; then
    fi
}
if [[ -n "$ZSH_VERSION" ]]; then
    autoload -U add-zsh-hook 2>/dev/null
    add-zsh-hook chpwd _es_wrapper_vm_hook
    _es_wrapper_vm_hook
fi
# <<< es-wrapper initialize <<<














# >>> Claude Code OpenTelemetry (managed) >>>
export OTEL_RESOURCE_ATTRIBUTES='x.event.source=o11y-ai,x.mdm.script.name=set_system_hooks,x.mdm.script.version=1.5.0'
export CLAUDE_CODE_ENABLE_TELEMETRY='1'
export CLAUDE_CODE_ENHANCED_TELEMETRY_BETA='1'
export OTEL_METRICS_EXPORTER='otlp'
export OTEL_METRIC_EXPORT_INTERVAL='10000'
export OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE='delta'
export OTEL_LOGS_EXPORTER='otlp'
export OTEL_LOGS_EXPORT_INTERVAL='5000'
export OTEL_TRACES_EXPORTER='otlp'
export OTEL_TRACES_EXPORT_INTERVAL='1000'
export OTEL_EXPORTER_OTLP_TRACES_PROTOCOL='http/protobuf'
export OTEL_EXPORTER_OTLP_TRACES_ENDPOINT='https://o11y-proxy-otel-ai.meli.com/v1/traces'
export OTEL_EXPORTER_OTLP_PROTOCOL='http/protobuf'
export OTEL_EXPORTER_OTLP_ENDPOINT='https://o11y-proxy-otel-ai.meli.com'
export OTEL_LOG_USER_PROMPTS='0'
export OTEL_LOG_TOOL_DETAILS='1'
# <<< Claude Code OpenTelemetry (managed) <<<

