command_timeout = 10000

# Inserts a blank line between shell prompts
add_newline = true

[character]
success_symbol = "[➜](bold fg:210)"
error_symbol = "[✗](bold red) "

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true
symbol = " "

[directory]
format = "[  $path]($style)[$read_only]($read_only_style) "
read_only = " "
style = "bold fg:210"

[git_branch]
format = "on [$branch]($style) "
style = "bold fg:222"
# symbol = " "
truncation_symbol = ""

[git_commit]
format = "[\\($hash\\)]($style) [\\($tag\\)]($style)"

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '

[git_status]
style = "bold fg:219"
ahead = " ⇡${count} "
behind = " ⇣${count} "
diverged = " ⇕${ahead_count}⇣${behind_count} "
deleted = " D${count} "
modified = " M${count} "
staged = '[++\($count\)](green)'
untracked = " U${count} "
stashed = " S${count} "

[golang]
symbol = "go "
# symbol = " "
# style = "bold fg:51"

[memory_usage]
symbol = " "

[python]
symbol = " "

[rust]
symbol = "rust "

[swift]
symbol = ' '

[nodejs]
disabled = true

[docker_context]
symbol = ""
# symbol = " "
